[package]
name = "trait-async"
version = "0.1.24"
authors = ["ㄗㄠˋ ㄑㄧˊ <tsao-chi@the-lingo.org>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Type erasure for async trait methods"
repository = "https://github.com/tsao-chi/trait-async"
documentation = "https://docs.rs/trait-async"
readme = "README.md"

[lib]
proc-macro = true

[badges]
travis-ci = { repository = "tsao-chi/trait-async" }

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full", "visit-mut"] }

[dev-dependencies]
rustversion = "1.0"
trybuild = { version = "1.0.19", features = ["diff"] }

[features]
# Alternative implementation that produces worse error messages but potentially
# works on old nightlies without https://github.com/rust-lang/rust/pull/61775 in
# some cases where the default implementation does not. This feature is semver
# exempt and might get removed without notice in any patch version.
support_old_nightly = []
